CALENDAR_EMPTY_CELL_COLOR = "#0f172a"
EVENT_STATUS_IMPORTANT = "important"
EVENT_STATUS_NORMAL = "normal"
EVENT_STATUS_KAIROS = "kairos"
EVENT_STATUS_DONE = "done"
EVENT_STATUS_LABELS = {
    EVENT_STATUS_NORMAL: "Normal",
    EVENT_STATUS_IMPORTANT: "Important",
    EVENT_STATUS_KAIROS: "Kairos",
    EVENT_STATUS_DONE: "Done",
}
EVENT_STATUS_COLORS = {
    EVENT_STATUS_IMPORTANT: "#ff6b6b",
    EVENT_STATUS_NORMAL: CALENDAR_EMPTY_CELL_COLOR,
    EVENT_STATUS_KAIROS: "#ffe66d",
    EVENT_STATUS_DONE: "#b8f75a",
}
EVENT_STATUS_TEXT_COLORS = {
    EVENT_STATUS_IMPORTANT: "#111827",
    EVENT_STATUS_NORMAL: "#ffffff",
    EVENT_STATUS_KAIROS: "#111827",
    EVENT_STATUS_DONE: "#111827",
}
EVENT_STATUS_TEXT_BOLD = {
    EVENT_STATUS_IMPORTANT: True,
    EVENT_STATUS_NORMAL: True,
    EVENT_STATUS_KAIROS: True,
    EVENT_STATUS_DONE: True,
}
